name: Docker Image CI

on:
  push:
    branches: [ functional ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set env from secret
      run: echo $DATABASE_URL_BASE64 | base64 -d > prisma/.env
      env:
        KEYSTORE_BASE64: ${{ secrets.DATABASE_URL_BASE64 }}
  
    - name: Build the Docker image
      run: docker-compose build     
    
    - name: Set docker hub access token
      run: echo $DOCKER_HUB_ACCESS_TOKEN > token.txt
      env: 
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Login and push to docker hub
      run: |
        cat token.txt | docker login --username $USERNAME --password-stdin
        docker tag docker.io/library/caskstore_api caskstore_api
        docker push $DOCKER_HUB_USERNAME/caskstore_api
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
