name: CI

on:
  push:
    branches:
      - main
      - functional

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      # Inits node project and adds modules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Installs all dependencies
      - name: Install dependencies
        run: npm install

      # Builds the documentation
      - name: Build Documentation
        run: |
          npx prisma generate
          npx typedoc src/*/* node_modules/@prisma/client/index.d.ts
      
      # Commits the new doc
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'docs'
